### ISSUE TITLE
Add a `docker-compose.yml` file that uses the redis-stack container

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/redis-caching-slow-database-queries#11]
Add a `docker-compose.yml` file that uses the `redis/redis-stack` container to the root of this repository, and amend the `README.md` file with instructions for how to start and stop Redis in the container with the `docker-compose` command.

For an example of a repository that has what we're looking for, see: https://github.com/redis-developer/redis-om-python-flask-skeleton-app

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by irvv17** [comment]
Hey @simonprickett and @SuzeShardlow I would like to work on this issue, Could you assign it to me?

**Comment by SuzeShardlow** [comment]
Hi @irvv17, I have assigned this to you.  Please check our guidelines, and we look forward to receiving your PR in a couple of days.  Have fun!

https://redis.io/community/hacktoberfest/

**Comment by SuzeShardlow** [comment]
Hi @irvv17, how are you doing with this?  :)

**Comment by irvv17** [comment]
> Hi @irvv17, how are you doing with this? :)

Hey, I will release a PR by today! Sorry for the delay

**Comment by SuzeShardlow** [comment]
Hi @irvv17, we haven't heard anything more from you so we are going to unassign this from you to give someone else a chance to work on it.

**Comment by SuzeShardlow** [comment]
This issue is up for grabs.  Please reply and tag me and @simonprickett if you would like to work on it :)

**Comment by irvv17** [comment]
Sorry for the delay, I just launch the PR in case I'm still able to solve this issue

cc @SuzeShardlow @simonprickett
