### ISSUE TITLE
Rewrite the node.js code to use the node-redis client.

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/redis-caching-slow-database-queries#13]
Rewrite the Node.js code in this repository to use the [node-redis](https://github.com/redis/node-redis/) client instead of ioredis.  When doing this, use `import` statements and top level `await`.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by codeDude64** [comment]
Hey @simonprickett  and @SuzeShardlow  I would like to work on this issue, Could you assign it to me?

**Comment by simonprickett** [comment]
@codeDude64 I've assigned this to you, looking forward to seeing your PR in the next couple of days. Have fun and please check out our guidelines:

https://redis.io/community/hacktoberfest/

**Comment by Vedant-Gandhi** [comment]
Hey @simonprickett  and @SuzeShardlow  can you assign the issue to me

**Comment by SuzeShardlow** [comment]
> Hey @simonprickett and @SuzeShardlow can you assign the issue to me

@Vedant-Gandhi no, we can't assign it to you, because it is already assigned to someone else.  Please check back in a day or two to see if it has become available again.  If there are no names under the `Assignees` heading (top right on desktop) then it is available.

**Comment by Vedant-Gandhi** [comment]
Okay

**Comment by SuzeShardlow** [comment]
Hi @codeDude64, how are you doing with this?

**Comment by codeDude64** [comment]
@SuzeShardlow I got problems with the project set up but in Discord, the team helped me solve them. Now I'm coding my solution. I keep communication with the team on Discord

**Comment by SuzeShardlow** [comment]
Cool, looking forward to seeing your PR @codeDude64 :)
